using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// 4xxxx
public enum TechnologyId
{
    POTTERY = TypeIdBase.TECHNOLOGY + EraId.ANCIENT,
    ANIMAL_HUSBANDRY,
    MINING,

    IRRIGATION,
    WRITING,
    ARCHERY,

    MASONRY,
    BRONZE_WORKING,
    WHEEL,

    CURRENCY = TypeIdBase.TECHNOLOGY + EraId.CLASSICAL,
    HORSEBACK_RIDING,
    IRON_WORKING,

    MATHEMATICS,
    CONSTRUCTION,
    ENGINEERING,

    MILITARY_TACTICS = TypeIdBase.TECHNOLOGY + EraId.MEDIEVAL,
    APPRENTICESHIP,
    MACHINERY,

    EDUCATION,
    STIRRUPS,
    MILITARY_ENGINEERING,
    CASTLES,

    MASS_PRODUCTION = TypeIdBase.TECHNOLOGY + EraId.RENAISSANCE,
    BANKING,
    PRINTING,
    GUNPOWDER,

    SIEGE_TACTICS,
    METAL_CASTING,
    ASTRONOMY,
}
